name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn clean verify

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        organization: jessicateles
        projectKey: jessicateles/GIMP_testing
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
